name: ABIF Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['1.6.0', 'stable']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
    
    - name: Install dependencies
      run: nimble install -y
      
    - name: Build
      run: nimble buildbin
      
    - name: Run tests
      run: nimble test
      
    - name: Generate docs
      run: nimble docs
      
    # Instead of using upload-artifact action, we'll just archive the files
    - name: Archive binaries
      run: |
        mkdir -p artifacts
        cp bin/abif bin/abi2fq artifacts/
        tar -czf abif-ubuntu-${{ matrix.nim-version }}.tar.gz artifacts/
        
    # Store the archive using the GitHub Actions cache
    - name: Store build artifacts
      uses: actions/cache@v3
      with:
        path: abif-ubuntu-${{ matrix.nim-version }}.tar.gz
        key: ${{ runner.os }}-nim${{ matrix.nim-version }}-${{ github.sha }}
